# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.price_and_availability_response_serviceresponse_responsepreamble import PriceAndAvailabilityResponseServiceresponseResponsepreamble  # noqa: E501
from swagger_client.rest import ApiException


class TestPriceAndAvailabilityResponseServiceresponseResponsepreamble(unittest.TestCase):
    """PriceAndAvailabilityResponseServiceresponseResponsepreamble unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceAndAvailabilityResponseServiceresponseResponsepreamble(self):
        """Test PriceAndAvailabilityResponseServiceresponseResponsepreamble"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.price_and_availability_response_serviceresponse_responsepreamble.PriceAndAvailabilityResponseServiceresponseResponsepreamble()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
