# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PriceAndAvailabilityResponseServiceresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'responsepreamble': 'PriceAndAvailabilityResponseServiceresponseResponsepreamble',
        'priceandstockresponse': 'PriceAndAvailabilityResponseServiceresponsePriceandstockresponse'
    }

    attribute_map = {
        'responsepreamble': 'responsepreamble',
        'priceandstockresponse': 'priceandstockresponse'
    }

    def __init__(self, responsepreamble=None, priceandstockresponse=None):  # noqa: E501
        """PriceAndAvailabilityResponseServiceresponse - a model defined in Swagger"""  # noqa: E501
        self._responsepreamble = None
        self._priceandstockresponse = None
        self.discriminator = None
        if responsepreamble is not None:
            self.responsepreamble = responsepreamble
        if priceandstockresponse is not None:
            self.priceandstockresponse = priceandstockresponse

    @property
    def responsepreamble(self):
        """Gets the responsepreamble of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501


        :return: The responsepreamble of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501
        :rtype: PriceAndAvailabilityResponseServiceresponseResponsepreamble
        """
        return self._responsepreamble

    @responsepreamble.setter
    def responsepreamble(self, responsepreamble):
        """Sets the responsepreamble of this PriceAndAvailabilityResponseServiceresponse.


        :param responsepreamble: The responsepreamble of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501
        :type: PriceAndAvailabilityResponseServiceresponseResponsepreamble
        """

        self._responsepreamble = responsepreamble

    @property
    def priceandstockresponse(self):
        """Gets the priceandstockresponse of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501


        :return: The priceandstockresponse of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501
        :rtype: PriceAndAvailabilityResponseServiceresponsePriceandstockresponse
        """
        return self._priceandstockresponse

    @priceandstockresponse.setter
    def priceandstockresponse(self, priceandstockresponse):
        """Sets the priceandstockresponse of this PriceAndAvailabilityResponseServiceresponse.


        :param priceandstockresponse: The priceandstockresponse of this PriceAndAvailabilityResponseServiceresponse.  # noqa: E501
        :type: PriceAndAvailabilityResponseServiceresponsePriceandstockresponse
        """

        self._priceandstockresponse = priceandstockresponse

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PriceAndAvailabilityResponseServiceresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PriceAndAvailabilityResponseServiceresponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
