# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PriceAndAvailabilityRequestServicerequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'requestpreamble': 'PriceAndAvailabilityRequestServicerequestRequestpreamble',
        'priceandstockrequest': 'PriceAndAvailabilityRequestServicerequestPriceandstockrequest'
    }

    attribute_map = {
        'requestpreamble': 'requestpreamble',
        'priceandstockrequest': 'priceandstockrequest'
    }

    def __init__(self, requestpreamble=None, priceandstockrequest=None):  # noqa: E501
        """PriceAndAvailabilityRequestServicerequest - a model defined in Swagger"""  # noqa: E501
        self._requestpreamble = None
        self._priceandstockrequest = None
        self.discriminator = None
        if requestpreamble is not None:
            self.requestpreamble = requestpreamble
        if priceandstockrequest is not None:
            self.priceandstockrequest = priceandstockrequest

    @property
    def requestpreamble(self):
        """Gets the requestpreamble of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501


        :return: The requestpreamble of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501
        :rtype: PriceAndAvailabilityRequestServicerequestRequestpreamble
        """
        return self._requestpreamble

    @requestpreamble.setter
    def requestpreamble(self, requestpreamble):
        """Sets the requestpreamble of this PriceAndAvailabilityRequestServicerequest.


        :param requestpreamble: The requestpreamble of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501
        :type: PriceAndAvailabilityRequestServicerequestRequestpreamble
        """

        self._requestpreamble = requestpreamble

    @property
    def priceandstockrequest(self):
        """Gets the priceandstockrequest of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501


        :return: The priceandstockrequest of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501
        :rtype: PriceAndAvailabilityRequestServicerequestPriceandstockrequest
        """
        return self._priceandstockrequest

    @priceandstockrequest.setter
    def priceandstockrequest(self, priceandstockrequest):
        """Sets the priceandstockrequest of this PriceAndAvailabilityRequestServicerequest.


        :param priceandstockrequest: The priceandstockrequest of this PriceAndAvailabilityRequestServicerequest.  # noqa: E501
        :type: PriceAndAvailabilityRequestServicerequestPriceandstockrequest
        """

        self._priceandstockrequest = priceandstockrequest

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PriceAndAvailabilityRequestServicerequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PriceAndAvailabilityRequestServicerequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
