# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PriceAndAvailabilityRequestServicerequestRequestpreamble(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'isocountrycode': 'str',
        'customernumber': 'str'
    }

    attribute_map = {
        'isocountrycode': 'isocountrycode',
        'customernumber': 'customernumber'
    }

    def __init__(self, isocountrycode=None, customernumber=None):  # noqa: E501
        """PriceAndAvailabilityRequestServicerequestRequestpreamble - a model defined in Swagger"""  # noqa: E501
        self._isocountrycode = None
        self._customernumber = None
        self.discriminator = None
        self.isocountrycode = isocountrycode
        self.customernumber = customernumber

    @property
    def isocountrycode(self):
        """Gets the isocountrycode of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501

        2 Digit ISO country code  # noqa: E501

        :return: The isocountrycode of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501
        :rtype: str
        """
        return self._isocountrycode

    @isocountrycode.setter
    def isocountrycode(self, isocountrycode):
        """Sets the isocountrycode of this PriceAndAvailabilityRequestServicerequestRequestpreamble.

        2 Digit ISO country code  # noqa: E501

        :param isocountrycode: The isocountrycode of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501
        :type: str
        """
        if isocountrycode is None:
            raise ValueError("Invalid value for `isocountrycode`, must not be `None`")  # noqa: E501

        self._isocountrycode = isocountrycode

    @property
    def customernumber(self):
        """Gets the customernumber of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501

        Your Ingram Micro customer number  # noqa: E501

        :return: The customernumber of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501
        :rtype: str
        """
        return self._customernumber

    @customernumber.setter
    def customernumber(self, customernumber):
        """Sets the customernumber of this PriceAndAvailabilityRequestServicerequestRequestpreamble.

        Your Ingram Micro customer number  # noqa: E501

        :param customernumber: The customernumber of this PriceAndAvailabilityRequestServicerequestRequestpreamble.  # noqa: E501
        :type: str
        """
        if customernumber is None:
            raise ValueError("Invalid value for `customernumber`, must not be `None`")  # noqa: E501

        self._customernumber = customernumber

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PriceAndAvailabilityRequestServicerequestRequestpreamble, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PriceAndAvailabilityRequestServicerequestRequestpreamble):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
