# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProductSearchResponseServiceresponseProductsearchresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'responseflag': 'str',
        'partnumbers': 'list[ProductSearchResponseServiceresponsePartnumbers]'
    }

    attribute_map = {
        'responseflag': 'responseflag',
        'partnumbers': 'partnumbers'
    }

    def __init__(self, responseflag=None, partnumbers=None):  # noqa: E501
        """ProductSearchResponseServiceresponseProductsearchresponse - a model defined in Swagger"""  # noqa: E501
        self._responseflag = None
        self._partnumbers = None
        self.discriminator = None
        if responseflag is not None:
            self.responseflag = responseflag
        if partnumbers is not None:
            self.partnumbers = partnumbers

    @property
    def responseflag(self):
        """Gets the responseflag of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501

        Number of records in the search result.  # noqa: E501

        :return: The responseflag of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501
        :rtype: str
        """
        return self._responseflag

    @responseflag.setter
    def responseflag(self, responseflag):
        """Sets the responseflag of this ProductSearchResponseServiceresponseProductsearchresponse.

        Number of records in the search result.  # noqa: E501

        :param responseflag: The responseflag of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501
        :type: str
        """

        self._responseflag = responseflag

    @property
    def partnumbers(self):
        """Gets the partnumbers of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501


        :return: The partnumbers of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501
        :rtype: list[ProductSearchResponseServiceresponsePartnumbers]
        """
        return self._partnumbers

    @partnumbers.setter
    def partnumbers(self, partnumbers):
        """Sets the partnumbers of this ProductSearchResponseServiceresponseProductsearchresponse.


        :param partnumbers: The partnumbers of this ProductSearchResponseServiceresponseProductsearchresponse.  # noqa: E501
        :type: list[ProductSearchResponseServiceresponsePartnumbers]
        """

        self._partnumbers = partnumbers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductSearchResponseServiceresponseProductsearchresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductSearchResponseServiceresponseProductsearchresponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
