# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProductSearchResponseServiceresponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'responsepreamble': 'ProductSearchResponseServiceresponseResponsepreamble',
        'productsearchresponse': 'list[ProductSearchResponseServiceresponseProductsearchresponse]'
    }

    attribute_map = {
        'responsepreamble': 'responsepreamble',
        'productsearchresponse': 'productsearchresponse'
    }

    def __init__(self, responsepreamble=None, productsearchresponse=None):  # noqa: E501
        """ProductSearchResponseServiceresponse - a model defined in Swagger"""  # noqa: E501
        self._responsepreamble = None
        self._productsearchresponse = None
        self.discriminator = None
        if responsepreamble is not None:
            self.responsepreamble = responsepreamble
        if productsearchresponse is not None:
            self.productsearchresponse = productsearchresponse

    @property
    def responsepreamble(self):
        """Gets the responsepreamble of this ProductSearchResponseServiceresponse.  # noqa: E501


        :return: The responsepreamble of this ProductSearchResponseServiceresponse.  # noqa: E501
        :rtype: ProductSearchResponseServiceresponseResponsepreamble
        """
        return self._responsepreamble

    @responsepreamble.setter
    def responsepreamble(self, responsepreamble):
        """Sets the responsepreamble of this ProductSearchResponseServiceresponse.


        :param responsepreamble: The responsepreamble of this ProductSearchResponseServiceresponse.  # noqa: E501
        :type: ProductSearchResponseServiceresponseResponsepreamble
        """

        self._responsepreamble = responsepreamble

    @property
    def productsearchresponse(self):
        """Gets the productsearchresponse of this ProductSearchResponseServiceresponse.  # noqa: E501


        :return: The productsearchresponse of this ProductSearchResponseServiceresponse.  # noqa: E501
        :rtype: list[ProductSearchResponseServiceresponseProductsearchresponse]
        """
        return self._productsearchresponse

    @productsearchresponse.setter
    def productsearchresponse(self, productsearchresponse):
        """Sets the productsearchresponse of this ProductSearchResponseServiceresponse.


        :param productsearchresponse: The productsearchresponse of this ProductSearchResponseServiceresponse.  # noqa: E501
        :type: list[ProductSearchResponseServiceresponseProductsearchresponse]
        """

        self._productsearchresponse = productsearchresponse

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductSearchResponseServiceresponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductSearchResponseServiceresponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
