# coding: utf-8

"""
    Product Catalog APIs

    Ingram Micro product catalog API for requesting price and availability of SKUs in real time.  *Production URL - https://api.ingrammicro.com:443/resellers/v5*  # noqa: E501

    OpenAPI spec version: 5.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ProductSearchResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'serviceresponse': 'ProductSearchResponseServiceresponse'
    }

    attribute_map = {
        'serviceresponse': 'serviceresponse'
    }

    def __init__(self, serviceresponse=None):  # noqa: E501
        """ProductSearchResponse - a model defined in Swagger"""  # noqa: E501
        self._serviceresponse = None
        self.discriminator = None
        if serviceresponse is not None:
            self.serviceresponse = serviceresponse

    @property
    def serviceresponse(self):
        """Gets the serviceresponse of this ProductSearchResponse.  # noqa: E501


        :return: The serviceresponse of this ProductSearchResponse.  # noqa: E501
        :rtype: ProductSearchResponseServiceresponse
        """
        return self._serviceresponse

    @serviceresponse.setter
    def serviceresponse(self, serviceresponse):
        """Sets the serviceresponse of this ProductSearchResponse.


        :param serviceresponse: The serviceresponse of this ProductSearchResponse.  # noqa: E501
        :type: ProductSearchResponseServiceresponse
        """

        self._serviceresponse = serviceresponse

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProductSearchResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProductSearchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
